"use client";

import { useState } from "react";
import type { Dispatch, SetStateAction } from "react";
import type { FacilityPerformance } from "../lib/platform-analytics";
import { roleTemplates } from "../lib/role-templates";

const platformModules = ["Core LIS workflow", "Payment & claims", "Analyzer integration", "Quality management", "Inventory & procurement", "Referral testing", "Clinical client portal", "Patient portal"];

export function FacilityOnboarding({ existingCodes, onClose, onComplete }: { existingCodes: string[]; onClose: () => void; onComplete: (facility: FacilityPerformance) => void }) {
  const [step, setStep] = useState(0);
  const [identity, setIdentity] = useState({ name: "", code: "", region: "Greater Accra", sites: "1", tier: "Professional", adminName: "", adminEmail: "" });
  const [modules, setModules] = useState(new Set(["Core LIS workflow", "Quality management", "Inventory & procurement"]));
  const [roles, setRoles] = useState(new Set(["facility_admin", "lab_manager", "receptionist", "phlebotomist", "pre_lab_scientist", "bench_scientist", "verifier", "quality_manager"]));
  const steps = ["Facility identity", "Modules", "Account types", "Administrator", "Review"];
  const code = identity.code.trim().toUpperCase();
  const stepValid = step === 0 ? identity.name.trim().length >= 3 && /^[A-Z0-9]{2,6}$/.test(code) && !existingCodes.includes(code) && Number(identity.sites) > 0 : step === 1 ? modules.has("Core LIS workflow") : step === 2 ? roles.has("facility_admin") && roles.has("verifier") : step === 3 ? identity.adminName.trim().length >= 3 && /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(identity.adminEmail) : true;
  const toggleSet = (setter: Dispatch<SetStateAction<Set<string>>>, current: Set<string>, value: string, locked = false) => { if (locked) return; setter(() => { const next = new Set(current); next.has(value) ? next.delete(value) : next.add(value); return next; }); };
  const complete = () => onComplete({ name: identity.name.trim(), code, region: identity.region, sites: Number(identity.sites), configuredStaff: 1, requiredStaff: Math.max(roles.size, 3), departments: roleTemplates.filter(item => roles.has(item.id) && item.category === "Laboratory").length, testsToday: 0, medianTatMinutes: 0, p95TatMinutes: 0, withinTatPercent: 0, qcState: "Setup", uptimePercent: 100 });

  return <div className="modal-backdrop" role="presentation"><div className="onboarding-modal" role="dialog" aria-modal="true" aria-label="Onboard facility"><div className="panel-head"><div><h2>Onboard a LabNett facility</h2><span>Provision the workspace, modules, account types and first administrator.</span></div><button className="icon-btn" onClick={onClose} aria-label="Close">×</button></div>
    <div className="onboarding-steps">{steps.map((item, index) => <button key={item} className={index === step ? "active" : index < step ? "done" : ""} onClick={() => index < step && setStep(index)}><i>{index < step ? "✓" : index + 1}</i><span>{item}</span></button>)}</div>
    <div className="onboarding-body">
      {step === 0 && <div className="form-grid"><label>Facility name *<input value={identity.name} onChange={event => setIdentity({ ...identity, name: event.target.value })} placeholder="e.g. Meridian Diagnostics" /></label><label>Facility code *<input value={identity.code} maxLength={6} onChange={event => setIdentity({ ...identity, code: event.target.value.toUpperCase() })} placeholder="MDL" /></label><label>Region<select value={identity.region} onChange={event => setIdentity({ ...identity, region: event.target.value })}><option>Greater Accra</option><option>Ashanti</option><option>Central</option><option>Eastern</option><option>Northern</option><option>Volta</option><option>Western</option></select></label><label>Initial sites / branches *<input type="number" min="1" value={identity.sites} onChange={event => setIdentity({ ...identity, sites: event.target.value })} /></label><label>Subscription tier<select value={identity.tier} onChange={event => setIdentity({ ...identity, tier: event.target.value })}><option>Core</option><option>Professional</option><option>Enterprise</option></select></label>{existingCodes.includes(code) && <div className="form-issues"><span>• Facility code already exists</span></div>}</div>}
      {step === 1 && <><div className="step-intro"><strong>Select facility modules</strong><span>The Core LIS workflow is required. Additional modules control which role templates and features can be activated.</span></div><div className="selection-grid">{platformModules.map(item => <label className={modules.has(item) ? "selected" : ""} key={item}><input type="checkbox" checked={modules.has(item)} disabled={item === "Core LIS workflow"} onChange={() => toggleSet(setModules, modules, item, item === "Core LIS workflow")} /><strong>{item}</strong><span>{item === "Core LIS workflow" ? "Required patient-to-report workflow" : `Provision ${item.toLowerCase()} tools`}</span></label>)}</div></>}
      {step === 2 && <><div className="step-intro"><strong>Select account types</strong><span>These global templates become available to the facility administrator. This does not create staff accounts.</span></div><div className="role-selection-grid">{roleTemplates.map(template => { const locked = Boolean(template.required); return <label className={roles.has(template.id) ? "selected" : ""} key={template.id}><input type="checkbox" checked={roles.has(template.id)} disabled={locked} onChange={() => toggleSet(setRoles, roles, template.id, locked)} /><span><strong>{template.name}</strong><small>{template.category} · {template.tier}{locked ? " · required" : ""}</small></span></label>; })}</div></>}
      {step === 3 && <><div className="step-intro"><strong>Create the first facility administrator</strong><span>This person receives a time-limited invitation and can then activate roles, configure units and invite staff.</span></div><div className="form-grid"><label>Administrator name *<input value={identity.adminName} onChange={event => setIdentity({ ...identity, adminName: event.target.value })} placeholder="Full name" /></label><label>Work email *<input type="email" value={identity.adminEmail} onChange={event => setIdentity({ ...identity, adminEmail: event.target.value })} placeholder="admin@facility.org" /></label><label>Initial role<input value="Facility Administrator" disabled /></label><label>Scope<input value={`${identity.name || "New facility"} · all initial sites`} disabled /></label></div><div className="clinical-warning"><strong>Software Owner does not become a facility user.</strong><span>The customer administrator owns patient operations, creates staff accounts and approves any future support access.</span></div></>}
      {step === 4 && <><div className="step-intro"><strong>Review before provisioning</strong><span>A draft facility is created with no patients, orders or clinical records.</span></div><div className="review-grid"><div><span>Facility</span><strong>{identity.name}</strong><small>{code} · {identity.region} · {identity.sites} site(s)</small></div><div><span>Subscription</span><strong>{identity.tier}</strong><small>{modules.size} modules selected</small></div><div><span>Account catalogue</span><strong>{roles.size} roles</strong><small>Includes Facility Administrator and Senior Scientist</small></div><div><span>Initial administrator</span><strong>{identity.adminName}</strong><small>{identity.adminEmail}</small></div></div><div className="provision-list"><p><i>✓</i><span><strong>Tenant and facility workspace</strong><small>Facility-isolated operational data boundary</small></span></p><p><i>✓</i><span><strong>Module and role entitlements</strong><small>Selected templates available to the facility administrator</small></span></p><p><i>✓</i><span><strong>Auditable administrator invitation</strong><small>No clinical access is granted to the Software Owner</small></span></p></div></>}
    </div>
    <div className="modal-actions"><button className="button" onClick={step === 0 ? onClose : () => setStep(step - 1)}>{step === 0 ? "Cancel" : "Back"}</button>{step < steps.length - 1 ? <button className="button primary" disabled={!stepValid} onClick={() => setStep(step + 1)}>Continue</button> : <button className="button primary" onClick={complete}>Provision facility</button>}</div>
  </div></div>;
}
