"use client";

import { useState } from "react";
import type { FacilityPerformance } from "../lib/platform-analytics";
import { performanceCsv } from "../lib/platform-analytics";
import type { SupportAccessRequest, SupportScope } from "../lib/support-access";
import { validateSupportAccess } from "../lib/support-access";

const unitNames = ["Reception & Accounts", "Pre-Lab", "Haematology", "Clinical Chemistry", "Microbiology", "Post-Lab", "Quality & Resources", "Equipment & Inventory"];

function exportFacility(row: FacilityPerformance) {
  const blob = new Blob([performanceCsv([row])], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a"); link.href = url; link.download = `${row.code.toLowerCase()}-facility-performance.csv`; link.click(); URL.revokeObjectURL(url);
}

export function PlatformFacilityDetail({ facility }: { facility: FacilityPerformance }) {
  const [requestOpen, setRequestOpen] = useState(false);
  const [requestState, setRequestState] = useState<"none" | "pending">("none");
  const [request, setRequest] = useState<SupportAccessRequest>({ facility: facility.name, ticket: `SUP-${facility.code}-01`, reason: "", scope: "technical_diagnostics", durationMinutes: 30, approver: "", acknowledged: false });
  const issues = validateSupportAccess(request);
  const update = <K extends keyof SupportAccessRequest>(field: K, value: SupportAccessRequest[K]) => setRequest(current => ({ ...current, [field]: value }));
  const branches = Array.from({ length: facility.sites }, (_, index) => ({ name: index === 0 ? "Main Branch" : `Branch ${index + 1}`, staff: Math.max(3, Math.round(facility.configuredStaff / facility.sites) - index), tests: Math.max(8, Math.round(facility.testsToday / facility.sites) - index * 7), state: index === facility.sites - 1 && facility.qcState === "Warning" ? "Attention" : "Operational" }));

  return <div className="content"><div className="page-head"><div><a className="back-link" href="/platform/facilities">← All onboarded facilities</a><div className="eyebrow">Software owner / facility aggregate</div><h1>{facility.name}</h1><p className="subtitle">{facility.code} · {facility.region} · Operational and configuration data only</p></div><div className="button-row"><span className="platform-boundary">Facility dashboard locked</span><button className="button" onClick={() => exportFacility(facility)}>Export facility</button><button className="button primary" disabled={requestState === "pending"} onClick={() => setRequestOpen(true)}>{requestState === "pending" ? "Support request pending" : "Request support access"}</button></div></div>

    <div className="metric-grid"><div className="metric"><div className="metric-top">Branches / sites</div><div className="metric-value">{facility.sites}</div><div className="metric-foot good">Registered on LabNett</div></div><div className="metric"><div className="metric-top">Configured staff</div><div className="metric-value">{facility.configuredStaff} / {facility.requiredStaff}</div><div className="metric-foot warn">{facility.requiredStaff - facility.configuredStaff} staffing gaps</div></div><div className="metric"><div className="metric-top">Laboratory units</div><div className="metric-value">{facility.departments}</div><div className="metric-foot">Configured analytical departments</div></div><div className="metric"><div className="metric-top">Tests today</div><div className="metric-value">{facility.testsToday}</div><div className="metric-foot good">{facility.withinTatPercent}% within target</div></div></div>

    {requestState === "pending" && <div className="support-request-card pending"><div className="support-request-main"><span className="support-request-icon">◷</span><div><strong>Support request sent to facility</strong><p>The facility administrator may approve or deny the requested scope and time.</p><small>{request.ticket} · {request.durationMinutes} minutes · Facility dashboard remains locked</small></div></div><a className="button small link-button" href="/platform/support">Track request</a></div>}

    <div className="network-chart-grid section-gap"><section className="panel"><div className="panel-head"><h2>Branch activity</h2><span>Tests received today</span></div><div className="facility-volume-chart">{branches.map(branch => <div key={branch.name}><span>{branch.name.replace(" Branch", "")}</span><i><b style={{ width: `${Math.min(100, branch.tests)}%` }} /></i><strong>{branch.tests}</strong></div>)}</div></section><section className="panel"><div className="panel-head"><h2>Turnaround time</h2><span>Facility performance against target</span></div><div className="tat-detail"><div><span>Median TAT</span><strong>{facility.medianTatMinutes} min</strong></div><div><span>P95 TAT</span><strong>{facility.p95TatMinutes} min</strong></div><div><span>Within target</span><strong>{facility.withinTatPercent}%</strong></div><div><span>Platform uptime</span><strong>{facility.uptimePercent}%</strong></div></div></section></div>

    <div className="network-chart-grid section-gap"><section className="panel"><div className="panel-head"><h2>Branches and staffing</h2><span>{facility.sites} configured locations</span></div><div className="table-wrap"><table><thead><tr><th>Branch</th><th>Configured staff</th><th>Tests today</th><th>Service state</th></tr></thead><tbody>{branches.map(branch => <tr key={branch.name}><td><strong>{facility.name} · {branch.name}</strong></td><td>{branch.staff}</td><td>{branch.tests}</td><td><span className={`status ${branch.state === "Operational" ? "green" : "amber"}`}>{branch.state}</span></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><h2>Configured operating units</h2><span>{facility.departments} analytical units</span></div><div className="unit-compact-list">{unitNames.map((unit, index) => <div key={unit}><i className={index < facility.departments || index < 2 || index > 4 ? "green" : "gray"} /><span><strong>{unit}</strong><small>{index < facility.departments || index < 2 || index > 4 ? "Configured and assigned" : "Not enabled at this facility"}</small></span></div>)}</div></section></div>

    <section className="panel section-gap"><div className="panel-head"><h2>Quality and platform service</h2><span>Aggregate status</span></div><div className="detail-grid modal-detail"><div className="detail-card"><span>QC state</span><strong>{facility.qcState}</strong></div><div className="detail-card"><span>Platform uptime</span><strong>{facility.uptimePercent}%</strong></div><div className="detail-card"><span>Staff configuration</span><strong>{Math.round(facility.configuredStaff / facility.requiredStaff * 100)}%</strong></div><div className="detail-card"><span>Dashboard access</span><strong>Not granted</strong></div></div><div className="assignment-preview"><strong>Need to perform maintenance?</strong><span>Request support access from this page. You can open the clinical facility dashboard only after its administrator grants the specified scope and duration.</span></div></section>

    {requestOpen && <div className="modal-backdrop" role="presentation"><form className="configuration-modal" role="dialog" aria-modal="true" aria-label={`Request support access to ${facility.name}`} onSubmit={event => { event.preventDefault(); if (!issues.length) { setRequestState("pending"); setRequestOpen(false); } }}><div className="panel-head"><div><h2>Request support access</h2><span>{facility.name} · facility approval required</span></div><button type="button" className="icon-btn" onClick={() => setRequestOpen(false)} aria-label="Close">×</button></div><div className="clinical-warning"><strong>This aggregate page does not grant access to the facility dashboard.</strong><span>Submit the minimum service scope and duration required. The facility can approve or deny it.</span></div><div className="form-grid"><label>Facility<input value={request.facility} disabled /></label><label>Support ticket *<input value={request.ticket} onChange={event => update("ticket", event.target.value)} /></label><label>Service scope *<select value={request.scope} onChange={event => update("scope", event.target.value as SupportScope)}><option value="technical_diagnostics">Maintenance and technical diagnostics</option><option value="configuration_read">Configuration review only</option><option value="patient_record_read">Specific record investigation · read-only</option></select></label><label>Access duration *<select value={request.durationMinutes} onChange={event => update("durationMinutes", Number(event.target.value))}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>1 hour maximum</option></select></label><label>Facility approver *<input value={request.approver} onChange={event => update("approver", event.target.value)} placeholder="Named facility administrator" /></label><label className="wide">Service reason *<textarea value={request.reason} onChange={event => update("reason", event.target.value)} placeholder="Explain the issue and exact maintenance work required." /></label><label className="wide support-ack"><input type="checkbox" checked={request.acknowledged} onChange={event => update("acknowledged", event.target.checked)} /> I accept that access is monitored, audited and automatically revoked.</label></div>{issues.length > 0 && <div className="form-issues">{issues.map(issue => <span key={issue}>• {issue}</span>)}</div>}<div className="modal-actions"><button type="button" className="button" onClick={() => setRequestOpen(false)}>Cancel</button><button type="submit" className="button primary" disabled={issues.length > 0}>Send to facility administrator</button></div></form></div>}
  </div>;
}
