"use client";

import { useState } from "react";
import type { RoleId, View } from "../lib/navigation";
import { roleDefinitions } from "../lib/navigation";
import { isUnitRole, UnitDashboard } from "./unit-dashboard";
import { PlatformDashboard } from "./platform-dashboard";

type DashboardConfig = {
  summary: string;
  metrics: [string, string, string, string][];
  queues: [string, string, string, "red" | "amber" | "blue" | "green", View][];
  actions: [string, View][];
};

function FacilitySupportRequest() {
  const [decision, setDecision] = useState<"pending" | "approved" | "denied">("pending");
  return <section className={`support-request-card ${decision}`}><div className="support-request-main"><span className="support-request-icon">{decision === "pending" ? "◷" : decision === "approved" ? "✓" : "×"}</span><div><strong>{decision === "pending" ? "Platform support access requested" : decision === "approved" ? "Temporary support access active" : "Support access denied"}</strong><p>{decision === "pending" ? "LabNett Support requests technical access to investigate the Mindray gateway retry queue." : decision === "approved" ? "SUP-2411 · Technical diagnostics · expires automatically in 30 minutes." : "SUP-2411 was denied. LabNett Support cannot open this facility workspace."}</p>{decision === "pending" && <small>SUP-2411 · 30 minutes · Technical diagnostics · requested by Kofi Asante</small>}</div></div>{decision === "pending" ? <div className="button-row"><button className="button" onClick={() => setDecision("denied")}>Deny</button><button className="button primary" onClick={() => setDecision("approved")}>Grant 30-minute access</button></div> : <button className="button small" onClick={() => setDecision("pending")}>View request history</button>}</section>;
}

const dashboards: Partial<Record<RoleId, DashboardConfig>> = {
  facility_admin: { summary: "Facility operations and configuration for Korle View Diagnostics.", metrics: [["Orders today", "96", "Across two branches", "▣"], ["Specimens active", "31", "Five marked STAT", "▤"], ["Results to verify", "14", "Senior review required", "✓"], ["Facility readiness", "86%", "Two setup tasks remain", "◇"]], queues: [["Result evaluation", "Analyzer and manual results in worklist", "14 cases", "amber", "worklist"], ["Analyzer warning", "Chemistry gateway retry queue", "6 queued", "red", "interfaces"], ["Onboarding task", "Approve the final report template", "1 task", "blue", "templates"]], actions: [["Create order", "orders"], ["Open worklists", "worklist"], ["Facility setup", "facility"]] },
  lab_manager: { summary: "Daily operations, staffing, TAT and clinical exceptions for LabNett Central.", metrics: [["Orders today", "128", "+12% vs yesterday", "▣"], ["In progress", "37", "Across 8 departments", "☷"], ["Awaiting verification", "23", "8 abnormal · 2 critical", "✓"], ["Staff on shift", "18 / 21", "Two gaps require cover", "♙"]], queues: [["Ageing work", "Cases approaching configured TAT", "11 cases", "amber", "worklist"], ["Critical results", "Notification and read-back required", "2 open", "red", "critical"], ["Shift coverage", "Chemistry evening bench needs cover", "2 gaps", "amber", "allocations"]], actions: [["Allocate work", "allocations"], ["Open worklists", "worklist"], ["Review TAT", "analytics"]] },
  receptionist: { summary: "Patient registration, order entry, authorization and specimen reception.", metrics: [["Waiting patients", "16", "Longest wait 24 min", "♙"], ["Orders to complete", "9", "3 need authorization", "▣"], ["Awaiting reception", "14", "6 marked STAT", "▤"], ["Labels to print", "7", "Collection desk 2", "□"]], queues: [["Possible duplicate", "Efua Ofori matches an existing record", "Review", "amber", "patients"], ["Insurance authorization", "Three orders awaiting response", "3 orders", "amber", "billing"], ["STAT reception", "Specimens waiting at reception desk", "6 tubes", "red", "reception"]], actions: [["Register patient", "patients"], ["Create order", "orders"], ["Receive specimen", "reception"]] },
  phlebotomist: { summary: "Identity-safe collection tasks, waiting times and collection exceptions.", metrics: [["Awaiting collection", "21", "5 marked STAT", "♧"], ["Collected today", "84", "Median wait 11 min", "✓"], ["Unable to collect", "2", "Reattempt scheduled", "!"], ["Tube stock", "1,240", "EDTA stock healthy", "□"]], queues: [["STAT collection", "Ama Mensah · FBC · EDTA", "8 min", "red", "collection"], ["Ward collection", "Four tasks in Medical Ward", "4 patients", "blue", "collection"], ["Recollection", "Wrong tube rejection requires recollection", "1 task", "amber", "collection"]], actions: [["Open collection list", "collection"], ["Find patient", "patients"], ["Check supplies", "inventory"]] },
  bench_scientist: { summary: "Assigned specimens, analyzer results and bench-level quality controls.", metrics: [["Assigned tests", "18", "3 STAT priority", "☷"], ["Results received", "7", "Ready for review", "◈"], ["Repeats", "2", "Reasons documented", "↻"], ["QC state", "Hold", "XN-330 Level 2 failed", "!"]], queues: [["Result review", "Ama Mensah · FBC · XN-330", "Ready", "blue", "results"], ["QC hold", "Haematology results are protected", "1 analyzer", "red", "quality"], ["Bench assignment", "Five unassigned routine accessions", "5 tests", "amber", "allocations"]], actions: [["My worklist", "worklist"], ["Review results", "results"], ["Open QC", "quality"]] },
  verifier: { summary: "Senior evaluation, clinical verification, critical-result communication and report release.", metrics: [["Results to evaluate", "31", "8 analyzer flags", "◈"], ["Awaiting verification", "23", "Oldest 21 min", "✓"], ["Critical", "2", "Communication open", "!"], ["Verified today", "62", "No amendments", "▥"]], queues: [["Result evaluation", "Analyzer results received into worklist", "8 cases", "amber", "worklist"], ["Critical verification", "Efua Ofori · Haemoglobin 5.1 g/dL", "6 min", "red", "verification"], ["Communication", "Potassium case past contact target", "Escalate", "red", "critical"]], actions: [["Results worklist", "worklist"], ["Verification queue", "verification"], ["Critical workspace", "critical"]] },
  quality_manager: { summary: "Quality control, equipment, nonconformities and laboratory governance.", metrics: [["QC failures", "1", "Corrective action open", "!"], ["Equipment due", "4", "Within 14 days", "▦"], ["Rejection rate", "1.8%", "Within facility target", "◩"], ["Audit actions", "7", "Quarterly review", "◷"]], queues: [["Corrective action", "XN CHECK Level 2 exceeds limit", "Open", "red", "quality"], ["Maintenance", "Hettich centrifuge is overdue", "3 days", "red", "equipment"], ["Policy review", "Downtime policy review is due", "Due today", "amber", "settings"]], actions: [["Quality dashboard", "quality"], ["Equipment", "equipment"], ["Audit evidence", "audit"]] },
  interface_engineer: { summary: "Analyzer connectivity, message safety, mappings and gateway health.", metrics: [["Analyzers online", "6 / 8", "One hold · one error", "◌"], ["Messages today", "2,941", "99.4% applied", "↔"], ["Unmatched", "2", "Manual investigation", "?"], ["Queue depth", "14", "Local sync retry active", "□"]], queues: [["Unknown sample", "Urit 50 · sample UR-558812", "Investigate", "red", "reconciliation"], ["Parse failure", "Mindray BS-240 · malformed segment", "4 events", "red", "interfaces"], ["Gateway queue", "GW-ACCRA-01 is synchronizing", "14 messages", "amber", "interfaces"]], actions: [["Interface monitor", "interfaces"], ["Unmatched results", "reconciliation"], ["Analyzer registry", "analyzers"]] },
  cashier_claims: { summary: "Payments, insurer authorization and claims queues without clinical-result access.", metrics: [["Payments pending", "9", "GHS 1,425 outstanding", "¤"], ["Claims awaiting", "3", "Insurer response required", "◷"], ["Receipts today", "74", "GHS 8,420 collected", "▧"], ["Reconciliation", "2", "End-of-shift exceptions", "!"]], queues: [["Pending payment", "Ama Mensah · ORD-2026-00821", "GHS 85", "amber", "billing"], ["Insurance authorization", "Three requests need follow-up", "3 claims", "amber", "billing"], ["Shift reconciliation", "Two receipts require review", "2 items", "red", "billing"]], actions: [["Payment and claims queue", "billing"]] },
  specimen_courier: { summary: "Assigned specimen routes, handovers, transport conditions and chain of custody.", metrics: [["Pickups assigned", "12", "Three marked STAT", "↗"], ["In transit", "7", "All seals confirmed", "□"], ["Due in 30 min", "2", "Korle View route", "◷"], ["Exceptions", "1", "Temperature review", "!"]], queues: [["STAT pickup", "East Legon Branch · sealed bag", "8 min", "red", "collection"], ["Facility handover", "Five specimens ready for dispatch", "5 bags", "blue", "referrals"], ["Transport exception", "Temperature logger requires review", "1 route", "amber", "reception"]], actions: [["My collection route", "collection"], ["Referral dispatch", "referrals"], ["Handover", "reception"]] },
  store_procurement: { summary: "Reagents, consumables, suppliers and purchase requests across assigned stores.", metrics: [["Stock items", "214", "Across two branch stores", "□"], ["Below reorder", "9", "Three critical", "!"], ["Expiring soon", "12", "Within 30 days", "◷"], ["Open requests", "5", "GHS 18,420", "▧"]], queues: [["Critical reorder", "Stromatolyser-FB below threshold", "2 packs", "red", "inventory"], ["Goods receipt", "Three supplier deliveries expected", "3 today", "blue", "inventory"], ["Cold storage", "Temperature evidence review", "1 event", "amber", "equipment"]], actions: [["Inventory", "inventory"], ["Receive stock", "inventory"], ["Equipment", "equipment"]] },
  biomedical_officer: { summary: "Equipment maintenance, calibration, downtime and service evidence.", metrics: [["Equipment", "42", "39 operational", "▦"], ["Service due", "4", "Within 14 days", "◷"], ["Downtime", "1", "Centrifuge unavailable", "!"], ["Calibration", "96%", "Current compliance", "✓"]], queues: [["Overdue service", "Hettich centrifuge · three days", "Overdue", "red", "equipment"], ["Analyzer warning", "Mindray BS-240 gateway retry", "Open", "amber", "analyzers"], ["Calibration evidence", "Finecare meter certificate", "Review", "blue", "quality"]], actions: [["Equipment registry", "equipment"], ["Analyzer registry", "analyzers"], ["Quality evidence", "quality"]] },
  referral_coordinator: { summary: "External-laboratory dispatch, tracking, returned results and referral accountability.", metrics: [["Awaiting dispatch", "6", "Two require cold chain", "↗"], ["In transit", "11", "Four referral laboratories", "□"], ["Results expected", "5", "Two due today", "◷"], ["Exceptions", "1", "Courier delay", "!"]], queues: [["Cold-chain dispatch", "Two molecular specimens", "11:30", "red", "referrals"], ["Returned report", "Histopathology report received", "Review", "blue", "reports"], ["Courier delay", "Tamale referral route", "46 min", "amber", "referrals"]], actions: [["Referral worklist", "referrals"], ["Receive specimen", "reception"], ["Returned reports", "reports"]] },
  ordering_clinician: { summary: "Orders and released reports limited to your patients and clinical organization.", metrics: [["Open requests", "8", "Two marked urgent", "▣"], ["Awaiting collection", "3", "Ward phlebotomy", "♧"], ["Reports released", "12", "Since last login", "▥"], ["Critical follow-up", "1", "Read-back required", "!"]], queues: [["Released report", "FBC · ward patient", "New", "blue", "reports"], ["Incomplete request", "Clinical note required", "1 order", "amber", "orders"], ["Critical read-back", "Named recipient confirmation", "Open", "red", "reports"]], actions: [["Create request", "orders"], ["My patients", "patients"], ["Released reports", "reports"]] },
  patient_portal: { summary: "Your released laboratory reports and notification preferences in one private view.", metrics: [["Released reports", "4", "Two this year", "▥"], ["Pending tests", "1", "Collection completed", "◷"], ["Unread reports", "1", "Ready to view", "!"], ["Profile", "Verified", "Identity confirmed", "✓"]], queues: [["New report", "Full Blood Count · released today", "View", "blue", "dashboard"], ["Pending order", "Renal Function · processing", "In progress", "amber", "dashboard"], ["Privacy", "Report access protected by verification", "Secure", "green", "dashboard"]], actions: [] },
  branch_admin: { summary: "Staffing, operations, TAT and configuration limited to East Legon Branch.", metrics: [["Orders today", "54", "Branch scope only", "▣"], ["Staff on shift", "9 / 11", "Two gaps", "♙"], ["Tests active", "18", "Across four units", "☷"], ["Within TAT", "94%", "Branch target", "◩"]], queues: [["Staffing gap", "Chemistry evening coverage", "1 role", "amber", "allocations"], ["Ageing work", "Three tests approaching TAT", "3 tests", "amber", "worklist"], ["Branch QC", "All active analyzers in control", "Clear", "green", "quality"]], actions: [["Branch orders", "orders"], ["Allocate staff", "allocations"], ["Branch analytics", "analytics"]] },
  auditor: { summary: "Time-limited, read-only access to approved audit and accreditation evidence.", metrics: [["Evidence items", "128", "Approved scope", "▧"], ["Open findings", "4", "Management response due", "!"], ["Policies sampled", "16", "Current review", "▥"], ["Access expires", "2 days", "Read only", "◷"]], queues: [["Evidence review", "Equipment maintenance sample", "12 items", "blue", "audit"], ["Open finding", "Competency evidence incomplete", "Finding 04", "amber", "audit"], ["TAT evidence", "Quarterly aggregate prepared", "Ready", "green", "analytics"]], actions: [["Audit evidence", "audit"], ["Aggregate analytics", "analytics"]] },
  privacy_officer: { summary: "Privacy incidents, access reviews and security events across authorized sites.", metrics: [["Access reviews", "7", "Due this quarter", "◷"], ["Denied access", "12", "Last 24 hours", "!"], ["Privacy incidents", "1", "Investigation open", "!"], ["Support sessions", "3", "All fully audited", "✓"]], queues: [["Access review", "Seven elevated accounts", "Due", "amber", "audit"], ["Denied patient read", "Unknown account · Korle View", "Investigate", "red", "audit"], ["Support audit", "SUP-2408 session evidence", "Complete", "green", "audit"]], actions: [["Privacy audit", "audit"]] },
};

function FacilityDashboard({ setView }: { setView: (view: View) => void }) {
  const flow = [["Orders", "96", "orders"], ["Collection", "18", "collection"], ["Reception", "11", "reception"], ["Testing", "31", "worklist"], ["Evaluation", "14", "results"], ["Verification", "9", "verification"], ["Released", "72", "reports"]] as const;
  const units = [["Reception & Accounts", "16 waiting · 3 claims", "billing", "green"], ["Pre-lab", "11 specimens · 2 held", "reception", "amber"], ["Haematology", "18 tests · QC hold", "worklist", "red"], ["Clinical Chemistry", "24 tests · 2 STAT", "worklist", "amber"], ["Microbiology", "7 cultures · day 2", "microbiology", "blue"], ["Post-lab", "14 evaluate · 9 verify", "verification", "amber"], ["Quality Control", "1 open corrective action", "quality", "red"], ["Inventory & Equipment", "3 stock alerts · 1 service", "inventory", "amber"]] as const;
  return <div className="content facility-dashboard">
    <section className="facility-hero">
      <div className="facility-identity"><div className="facility-logo">KV</div><div><span>FACILITY WORKSPACE</span><h1>Korle View Diagnostics</h1><p>Accra Main Branch · Facility code KVD · Diagnostic laboratory</p></div></div>
      <div className="facility-hero-actions"><span className="facility-live">● Operational</span><button className="button" onClick={() => setView("facility")}>Facility settings</button><button className="button primary" onClick={() => setView("orders")}>+ New order</button></div>
    </section>

    <div className="facility-context"><div><span>Current branch</span><strong>Accra Main Branch ▾</strong></div><div><span>Shift</span><strong>Day · 08:00–16:00</strong></div><div><span>Laboratory manager</span><strong>Akua Sarpong</strong></div><div><span>Last synchronized</span><strong>Just now</strong></div></div>

    <FacilitySupportRequest />

    <div className="metric-grid section-gap"><div className="metric"><div className="metric-top"><span>Orders today</span><i className="metric-icon">▣</i></div><div className="metric-value">96</div><div className="metric-foot good">12% above weekday average</div></div><div className="metric"><div className="metric-top"><span>Tests in progress</span><i className="metric-icon">☷</i></div><div className="metric-value">31</div><div className="metric-foot warn">Five approaching TAT</div></div><div className="metric"><div className="metric-top"><span>Results to verify</span><i className="metric-icon">✓</i></div><div className="metric-value">14</div><div className="metric-foot warn">Two abnormal · one critical</div></div><div className="metric"><div className="metric-top"><span>Reports released</span><i className="metric-icon">▥</i></div><div className="metric-value">72</div><div className="metric-foot good">95% within target TAT</div></div></div>

    <section className="panel"><div className="panel-head"><h2>Facility unit operations</h2><button className="text-action" onClick={() => setView("facility-setup")}>Configure operating model</button></div><div className="unit-overview-grid">{units.map(([name, summary, view, tone]) => <button key={name} onClick={() => setView(view)}><i className={tone} /><span><strong>{name}</strong><small>{summary}</small></span><b>→</b></button>)}</div></section>

    <section className="panel section-gap"><div className="panel-head"><h2>Today’s laboratory flow</h2><span>Live workload by stage</span></div><div className="facility-flow">{flow.map(([label, value, view], index) => <div className="facility-flow-wrap" key={label}><button className="facility-flow-step" onClick={() => setView(view)}><span>{value}</span><strong>{label}</strong></button>{index < flow.length - 1 && <i>→</i>}</div>)}</div></section>

    <div className="facility-main-grid section-gap"><section className="panel"><div className="panel-head"><h2>Priority work</h2><button className="text-action" onClick={() => setView("worklist")}>View all work →</button></div><div className="table-wrap"><table><thead><tr><th>Accession</th><th>Patient</th><th>Test</th><th>Department</th><th>TAT</th><th>Status</th></tr></thead><tbody><tr><td><strong>HM-260908-01572</strong></td><td>Ama Serwaa</td><td>FBC</td><td>Haematology</td><td><span className="tat urgent">12 min left</span></td><td><span className="status amber">Evaluation</span></td></tr><tr><td><strong>CH-260908-00431</strong></td><td>Kweku Mensah</td><td>Electrolytes</td><td>Chemistry</td><td><span className="tat urgent">STAT · 8 min</span></td><td><span className="status red">Critical</span></td></tr><tr><td><strong>MB-260908-00322</strong></td><td>Naa Dedei</td><td>Urine Culture</td><td>Microbiology</td><td><span className="tat">Day 2 of 3</span></td><td><span className="status blue">Incubation</span></td></tr><tr><td><strong>CH-260908-00428</strong></td><td>Yaw Owusu</td><td>Renal Function</td><td>Chemistry</td><td><span className="tat">1 h 22 min</span></td><td><span className="status blue">Running</span></td></tr></tbody></table></div></section>
      <aside className="facility-side-stack"><section className="panel"><div className="panel-head"><h2>Analyzer health</h2><button className="text-action" onClick={() => setView("analyzers")}>Open registry</button></div><div className="device-list"><div><i className="online" /><span><strong>Sysmex XN-330</strong><small>Haematology · 18 sec ago</small></span><b>Online</b></div><div><i className="warning" /><span><strong>Mindray BS-240</strong><small>Chemistry · 6 queued</small></span><b>Warning</b></div><div><i className="online" /><span><strong>Finecare FIA</strong><small>Immunology · 2 min ago</small></span><b>Online</b></div></div></section><section className="panel"><div className="panel-head"><h2>Staff on shift</h2><button className="text-action" onClick={() => setView("allocations")}>Allocate</button></div><div className="staff-summary"><strong>18 <span>/ 21 required</span></strong><div className="staff-bar"><i style={{ width: "86%" }} /></div><p>Chemistry evening bench needs one qualified scientist.</p></div></section></aside>
    </div>

    <div className="facility-bottom-grid section-gap"><section className="panel"><div className="panel-head"><h2>Facility readiness</h2><span>86% configured</span></div><div className="readiness"><div className="readiness-ring"><strong>86%</strong><span>ready</span></div><div className="readiness-items"><p><i className="done">✓</i><span><strong>Facility identity and branding</strong><small>Logo, contact and report header approved</small></span></p><p><i className="done">✓</i><span><strong>Departments and users</strong><small>Eight departments · 22 active users</small></span></p><p><i className="pending">!</i><span><strong>Analyzer validation</strong><small>Two of three analyzers validated</small></span></p><p><i className="pending">!</i><span><strong>Report template approval</strong><small>Clinical report v2 awaiting sign-off</small></span></p></div></div></section><section className="panel"><div className="panel-head"><h2>Turnaround time</h2><button className="text-action" onClick={() => setView("analytics")}>Full analytics</button></div><div className="tat-overview"><div><span>Median</span><strong>51 min</strong><small>↓ 7 min this week</small></div><div><span>P95</span><strong>3 h 12 m</strong><small>Target: under 4 h</small></div><div><span>Within target</span><strong>95%</strong><small>72 reports today</small></div></div><div className="mini-bars">{[54, 70, 62, 81, 76, 68, 88].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div></section></div>
  </div>;
}

export function RoleDashboard({ role, setView }: { role: RoleId; setView: (view: View) => void }) {
  if (role === "main_admin") return <PlatformDashboard setView={setView} />;
  if (role === "facility_admin") return <FacilityDashboard setView={setView} />;
  if (isUnitRole(role)) return <UnitDashboard role={role} setView={setView} />;
  const config = dashboards[role]!;
  const identity = roleDefinitions[role];
  return <div className="content">
    <div className="page-head"><div><div className="eyebrow">Monday, 08 September 2026 · {identity.label}</div><h1>Good morning, {identity.name.split(" ")[0]}</h1><p className="subtitle">{config.summary}</p></div><div className="button-row">{config.actions.map(([label, view], index) => <button key={label} className={`button ${index === 0 ? "primary" : ""}`} onClick={() => setView(view)}>{index === 0 ? "+ " : ""}{label}</button>)}</div></div>
    <div className="metric-grid">{config.metrics.map(([label, value, note, icon]) => <div className="metric" key={label}><div className="metric-top"><span>{label}</span><i className="metric-icon">{icon}</i></div><div className="metric-value">{value}</div><div className="metric-foot">{note}</div></div>)}</div>
    <div className="dashboard-grid"><div className="panel"><div className="panel-head"><h2>My priority queues</h2><span>Role and scope filtered</span></div><div className="queue">{config.queues.map(([title, copy, value, tone, view]) => <button className="queue-item queue-button" key={title} onClick={() => setView(view)}><div className={`queue-symbol ${tone}`}>{tone === "red" ? "!" : tone === "amber" ? "◷" : "→"}</div><div className="queue-copy"><strong>{title}</strong><span>{copy}</span></div><div className="queue-value">{value}</div><span className={`status ${tone}`}>Open</span></button>)}</div></div><div className="panel"><div className="panel-head"><h2>Current access</h2><span>Permission aware</span></div><div className="role-access"><div className="role-avatar">{identity.name.split(" ").map(word => word[0]).join("").slice(0, 2)}</div><strong>{identity.name}</strong><span>{identity.label}</span><small>{identity.scope}</small><div className="access-note">Navigation and actions are restricted to this role. Backend authorization must enforce the same rules.</div></div></div></div>
  </div>;
}
