"use client";

import { useMemo, useState } from "react";
import type { SupportAccessRequest, SupportScope } from "../lib/support-access";
import { validateSupportAccess } from "../lib/support-access";

type Ticket = { id: string; facility: string; service: string; requested: string; duration: string; state: "Pending" | "Approved" | "Denied" | "Expired"; owner: string };

const initialTickets: Ticket[] = [
  { id: "SUP-2414", facility: "Aseda Community Laboratory", service: "Catalogue import assistance", requested: "12 min ago", duration: "30 min", state: "Pending", owner: "Kofi Asante" },
  { id: "SUP-2411", facility: "Korle View Diagnostics", service: "Gateway diagnostics", requested: "42 min ago", duration: "30 min", state: "Pending", owner: "Kofi Asante" },
  { id: "SUP-2408", facility: "NorthStar Medical Lab", service: "Report template maintenance", requested: "Today · 19:58", duration: "60 min", state: "Approved", owner: "Daniel Tetteh" },
  { id: "SUP-2399", facility: "LabNett Central", service: "Interface log review", requested: "Yesterday · 14:20", duration: "15 min", state: "Expired", owner: "Daniel Tetteh" },
];

const emptyRequest: SupportAccessRequest = { facility: "Korle View Diagnostics", ticket: "", reason: "", scope: "technical_diagnostics", durationMinutes: 30, approver: "", acknowledged: false };

export function SupportMaintenanceScreen() {
  const [tickets, setTickets] = useState(initialTickets);
  const [query, setQuery] = useState("");
  const [state, setState] = useState("All states");
  const [requestOpen, setRequestOpen] = useState(false);
  const [request, setRequest] = useState(emptyRequest);
  const [selected, setSelected] = useState<Ticket | null>(null);
  const issues = validateSupportAccess(request);
  const visible = useMemo(() => tickets.filter(ticket => (state === "All states" || ticket.state === state) && Object.values(ticket).join(" ").toLowerCase().includes(query.toLowerCase())), [query, state, tickets]);
  const update = <K extends keyof SupportAccessRequest>(field: K, value: SupportAccessRequest[K]) => setRequest(current => ({ ...current, [field]: value }));
  const submit = () => {
    if (issues.length) return;
    setTickets(current => [{ id: request.ticket, facility: request.facility, service: request.scope === "technical_diagnostics" ? "Maintenance and technical diagnostics" : request.scope === "configuration_read" ? "Configuration review" : "Specific record investigation", requested: "Just now", duration: `${request.durationMinutes} min`, state: "Pending", owner: "Kofi Asante" }, ...current]);
    setRequestOpen(false); setRequest(emptyRequest);
  };

  return <div className="content"><div className="page-head"><div><div className="eyebrow">Platform / customer service</div><h1>Support & maintenance</h1><p className="subtitle">Request, monitor and audit time-limited service access without automatic entry into customer facilities.</p></div><div className="button-row"><span className="platform-boundary">No facility access by default</span><button className="button primary" onClick={() => setRequestOpen(true)}>+ New support request</button></div></div>
    <div className="metric-grid"><div className="metric"><div className="metric-top">Open requests</div><div className="metric-value">3</div><div className="metric-foot warn">2 awaiting facility approval</div></div><div className="metric"><div className="metric-top">Active sessions</div><div className="metric-value">1</div><div className="metric-foot good">Expires automatically</div></div><div className="metric"><div className="metric-top">Resolved this month</div><div className="metric-value">47</div><div className="metric-foot good">Median resolution 38 min</div></div><div className="metric"><div className="metric-top">Access exceptions</div><div className="metric-value">0</div><div className="metric-foot good">All sessions audited</div></div></div>
    <section className="panel"><div className="panel-head"><h2>Service request register</h2><span>Requests, approvals, denials and expiry</span></div><div className="toolbar"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search ticket, facility or service" /><select value={state} onChange={event => setState(event.target.value)}><option>All states</option><option>Pending</option><option>Approved</option><option>Denied</option><option>Expired</option></select><span className="scope-lock">Facility dashboards locked unless approved</span></div><div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Facility</th><th>Service</th><th>Requested</th><th>Duration</th><th>Requester</th><th>Access state</th><th /></tr></thead><tbody>{visible.map(ticket => <tr key={ticket.id}><td><strong>{ticket.id}</strong></td><td>{ticket.facility}</td><td>{ticket.service}</td><td>{ticket.requested}</td><td>{ticket.duration}</td><td>{ticket.owner}</td><td><span className={`status ${ticket.state === "Approved" ? "green" : ticket.state === "Pending" ? "amber" : ticket.state === "Denied" ? "red" : "gray"}`}>{ticket.state}</span></td><td>{ticket.state === "Approved" ? <a className="button small primary link-button" href="/facility">Open approved session</a> : <button className="button small" onClick={() => setSelected(ticket)}>View</button>}</td></tr>)}</tbody></table>{visible.length === 0 && <div className="empty-table"><strong>No matching service requests</strong><span>Change the search or access-state filter.</span></div>}</div></section>
    <div className="permission-note section-gap"><strong>Access rule</strong><span>A service request does not unlock a facility. The named facility administrator must approve it, and access automatically ends after the approved duration. Denied, pending and expired requests cannot open a facility dashboard.</span></div>

    {requestOpen && <div className="modal-backdrop" role="presentation"><form className="configuration-modal" role="dialog" aria-modal="true" aria-label="New support request" onSubmit={event => { event.preventDefault(); submit(); }}><div className="panel-head"><div><h2>New support request</h2><span>The selected facility can approve or deny this request.</span></div><button type="button" className="icon-btn" onClick={() => setRequestOpen(false)} aria-label="Close">×</button></div><div className="clinical-warning"><strong>The facility dashboard remains locked until approval.</strong><span>Request only the minimum scope and time required to complete the service.</span></div><div className="form-grid"><label>Facility *<select value={request.facility} onChange={event => update("facility", event.target.value)}><option>Korle View Diagnostics</option><option>LabNett Central</option><option>NorthStar Medical Lab</option><option>Aseda Community Laboratory</option></select></label><label>Support ticket *<input value={request.ticket} onChange={event => update("ticket", event.target.value)} placeholder="SUP-0000" /></label><label>Service scope *<select value={request.scope} onChange={event => update("scope", event.target.value as SupportScope)}><option value="technical_diagnostics">Maintenance and technical diagnostics</option><option value="configuration_read">Configuration review only</option><option value="patient_record_read">Specific record investigation · read-only</option></select></label><label>Requested time *<select value={request.durationMinutes} onChange={event => update("durationMinutes", Number(event.target.value))}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>1 hour maximum</option></select></label><label>Facility approver *<input value={request.approver} onChange={event => update("approver", event.target.value)} placeholder="Named facility administrator" /></label><label className="wide">Service reason *<textarea value={request.reason} onChange={event => update("reason", event.target.value)} placeholder="Describe the issue and the exact work to be completed." /></label><label className="wide support-ack"><input type="checkbox" checked={request.acknowledged} onChange={event => update("acknowledged", event.target.checked)} /> I acknowledge that the session is monitored, audited, purpose-limited and automatically revoked.</label></div>{issues.length > 0 && <div className="form-issues">{issues.map(issue => <span key={issue}>• {issue}</span>)}</div>}<div className="modal-actions"><button type="button" className="button" onClick={() => setRequestOpen(false)}>Cancel</button><button type="submit" className="button primary" disabled={issues.length > 0}>Send to facility</button></div></form></div>}
    {selected && <div className="modal-backdrop" role="presentation"><div className="configuration-modal compact" role="dialog" aria-modal="true" aria-label={`${selected.id} details`}><div className="panel-head"><div><h2>{selected.id}</h2><span>{selected.facility}</span></div><button className="icon-btn" onClick={() => setSelected(null)} aria-label="Close">×</button></div><div className="detail-grid modal-detail"><div className="detail-card"><span>Service</span><strong>{selected.service}</strong></div><div className="detail-card"><span>Requested duration</span><strong>{selected.duration}</strong></div><div className="detail-card"><span>Access state</span><strong>{selected.state}</strong></div><div className="detail-card"><span>Dashboard access</span><strong>{selected.state === "Approved" ? "Available until expiry" : "Locked"}</strong></div></div><div className="modal-actions"><button className="button primary" onClick={() => setSelected(null)}>Done</button></div></div></div>}
  </div>;
}
